/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module lifo(dataIn, dataOut, RW, EN, Rst, EMPTY, FULL, clk);
  wire _000_;
  wire _001_;
  wire [2:0] _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire [3:0] _005_;
  wire [3:0] _006_;
  wire [3:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  output EMPTY;
  input EN;
  output FULL;
  input RW;
  input Rst;
  wire [2:0] SP;
  input clk;
  input [3:0] dataIn;
  output [3:0] dataOut;
  wire [3:0] \stack_mem[0] ;
  wire [3:0] \stack_mem[1] ;
  wire [3:0] \stack_mem[2] ;
  wire [3:0] \stack_mem[3] ;
  sky130_fd_sc_hd__clkinv_1 _092_ (
    .A(SP[2]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _093_ (
    .A(\stack_mem[3] [0]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _094_ (
    .A(\stack_mem[3] [1]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _095_ (
    .A(\stack_mem[3] [2]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _096_ (
    .A(\stack_mem[3] [3]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _097_ (
    .A(\stack_mem[2] [0]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _098_ (
    .A(\stack_mem[2] [1]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _099_ (
    .A(\stack_mem[2] [2]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _100_ (
    .A(\stack_mem[2] [3]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _101_ (
    .A(\stack_mem[1] [0]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _102_ (
    .A(\stack_mem[1] [1]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _103_ (
    .A(\stack_mem[1] [2]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _104_ (
    .A(\stack_mem[1] [3]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _105_ (
    .A(dataOut[0]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _106_ (
    .A(dataOut[1]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _107_ (
    .A(dataOut[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(dataOut[3]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(EMPTY),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(SP[1]),
    .B(SP[0]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _111_ (
    .A(SP[1]),
    .SLEEP(SP[0]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor3_1 _112_ (
    .A(SP[2]),
    .B(SP[1]),
    .C(SP[0]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _113_ (
    .A(RW),
    .SLEEP(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _114_ (
    .A(_054_),
    .B(RW),
    .C(_073_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__or3_1 _115_ (
    .A(_054_),
    .B(RW),
    .C(_073_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and2_0 _116_ (
    .A(SP[1]),
    .B(SP[0]),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(SP[1]),
    .B(SP[0]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2b_1 _118_ (
    .A_N(SP[2]),
    .B(RW),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand3_1 _119_ (
    .A(_054_),
    .B(RW),
    .C(_078_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _120_ (
    .A(EN),
    .SLEEP(Rst),
    .X(_082_)
  );
  sky130_fd_sc_hd__nand2b_1 _121_ (
    .A_N(Rst),
    .B(EN),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21ai_0 _122_ (
    .A1(dataIn[0]),
    .A2(_077_),
    .B1(_081_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(\stack_mem[3] [0]),
    .A2(_076_),
    .B1(_082_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o22ai_1 _124_ (
    .A1(_055_),
    .A2(EN),
    .B1(_084_),
    .B2(_085_),
    .Y(_007_[0])
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(dataIn[1]),
    .B(_077_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a21oi_1 _126_ (
    .A1(\stack_mem[3] [1]),
    .A2(_081_),
    .B1(_076_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o32ai_1 _127_ (
    .A1(_083_),
    .A2(_086_),
    .A3(_087_),
    .B1(_056_),
    .B2(EN),
    .Y(_007_[1])
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(dataIn[2]),
    .B(_077_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _129_ (
    .A1(\stack_mem[3] [2]),
    .A2(_081_),
    .B1(_076_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o32ai_1 _130_ (
    .A1(_083_),
    .A2(_088_),
    .A3(_089_),
    .B1(_057_),
    .B2(EN),
    .Y(_007_[2])
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(dataIn[3]),
    .B(_077_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _132_ (
    .A1(\stack_mem[3] [3]),
    .A2(_081_),
    .B1(_076_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__o32ai_1 _133_ (
    .A1(_083_),
    .A2(_090_),
    .A3(_091_),
    .B1(_058_),
    .B2(EN),
    .Y(_007_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _134_ (
    .A(SP[0]),
    .SLEEP(SP[1]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2b_1 _135_ (
    .A_N(SP[1]),
    .B(SP[0]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor3_1 _136_ (
    .A(RW),
    .B(_083_),
    .C(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o221ai_1 _137_ (
    .A1(_073_),
    .A2(_080_),
    .B1(_009_),
    .B2(RW),
    .C1(_082_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _138_ (
    .A(EN),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a22o_1 _139_ (
    .A1(dataIn[0]),
    .A2(_010_),
    .B1(_012_),
    .B2(\stack_mem[0] [0]),
    .X(_004_[0])
  );
  sky130_fd_sc_hd__a22o_1 _140_ (
    .A1(dataIn[1]),
    .A2(_010_),
    .B1(_012_),
    .B2(\stack_mem[0] [1]),
    .X(_004_[1])
  );
  sky130_fd_sc_hd__a22o_1 _141_ (
    .A1(dataIn[2]),
    .A2(_010_),
    .B1(_012_),
    .B2(\stack_mem[0] [2]),
    .X(_004_[2])
  );
  sky130_fd_sc_hd__a22o_1 _142_ (
    .A1(dataIn[3]),
    .A2(_010_),
    .B1(_012_),
    .B2(\stack_mem[0] [3]),
    .X(_004_[3])
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(RW),
    .B(_079_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(\stack_mem[2] [0]),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _145_ (
    .A(dataIn[0]),
    .B(_075_),
    .C(_079_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _146_ (
    .A(SP[1]),
    .SLEEP(SP[0]),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2b_1 _147_ (
    .A_N(SP[0]),
    .B(SP[1]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(_080_),
    .A2(_017_),
    .B1(_082_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o32ai_1 _149_ (
    .A1(_014_),
    .A2(_015_),
    .A3(_018_),
    .B1(_059_),
    .B2(EN),
    .Y(_006_[0])
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(\stack_mem[2] [1]),
    .B(_013_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor3_1 _151_ (
    .A(dataIn[1]),
    .B(_075_),
    .C(_079_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o32ai_1 _152_ (
    .A1(_018_),
    .A2(_019_),
    .A3(_020_),
    .B1(_060_),
    .B2(EN),
    .Y(_006_[1])
  );
  sky130_fd_sc_hd__nor2_1 _153_ (
    .A(\stack_mem[2] [2]),
    .B(_013_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(dataIn[2]),
    .B(_075_),
    .C(_079_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o32ai_1 _155_ (
    .A1(_018_),
    .A2(_021_),
    .A3(_022_),
    .B1(_061_),
    .B2(EN),
    .Y(_006_[2])
  );
  sky130_fd_sc_hd__nor2_1 _156_ (
    .A(\stack_mem[2] [3]),
    .B(_013_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3_1 _157_ (
    .A(dataIn[3]),
    .B(_075_),
    .C(_079_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o32ai_1 _158_ (
    .A1(_018_),
    .A2(_023_),
    .A3(_024_),
    .B1(_062_),
    .B2(EN),
    .Y(_006_[3])
  );
  sky130_fd_sc_hd__nor2_1 _159_ (
    .A(RW),
    .B(_017_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _160_ (
    .A(\stack_mem[1] [0]),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _161_ (
    .A(dataIn[0]),
    .B(_075_),
    .C(_017_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _162_ (
    .A1(_080_),
    .A2(_009_),
    .B1(_082_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o32ai_1 _163_ (
    .A1(_026_),
    .A2(_027_),
    .A3(_028_),
    .B1(_063_),
    .B2(EN),
    .Y(_005_[0])
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(\stack_mem[1] [1]),
    .B(_025_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor3_1 _165_ (
    .A(dataIn[1]),
    .B(_075_),
    .C(_017_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o32ai_1 _166_ (
    .A1(_028_),
    .A2(_029_),
    .A3(_030_),
    .B1(_064_),
    .B2(EN),
    .Y(_005_[1])
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(\stack_mem[1] [2]),
    .B(_025_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor3_1 _168_ (
    .A(dataIn[2]),
    .B(_075_),
    .C(_017_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o32ai_1 _169_ (
    .A1(_028_),
    .A2(_031_),
    .A3(_032_),
    .B1(_065_),
    .B2(EN),
    .Y(_005_[2])
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(\stack_mem[1] [3]),
    .B(_025_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _171_ (
    .A(dataIn[3]),
    .B(_075_),
    .C(_017_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o32ai_1 _172_ (
    .A1(_028_),
    .A2(_033_),
    .A3(_034_),
    .B1(_066_),
    .B2(EN),
    .Y(_005_[3])
  );
  sky130_fd_sc_hd__a222oi_1 _173_ (
    .A1(\stack_mem[0] [0]),
    .A2(_072_),
    .B1(_016_),
    .B2(\stack_mem[2] [0]),
    .C1(_078_),
    .C2(\stack_mem[3] [0]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21boi_0 _174_ (
    .A1(\stack_mem[1] [0]),
    .A2(_008_),
    .B1_N(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o22ai_1 _175_ (
    .A1(EN),
    .A2(_067_),
    .B1(_083_),
    .B2(_036_),
    .Y(_003_[0])
  );
  sky130_fd_sc_hd__a222oi_1 _176_ (
    .A1(\stack_mem[0] [1]),
    .A2(_072_),
    .B1(_008_),
    .B2(\stack_mem[1] [1]),
    .C1(_016_),
    .C2(\stack_mem[2] [1]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21boi_0 _177_ (
    .A1(\stack_mem[3] [1]),
    .A2(_078_),
    .B1_N(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o22ai_1 _178_ (
    .A1(EN),
    .A2(_068_),
    .B1(_083_),
    .B2(_038_),
    .Y(_003_[1])
  );
  sky130_fd_sc_hd__a222oi_1 _179_ (
    .A1(\stack_mem[0] [2]),
    .A2(_072_),
    .B1(_008_),
    .B2(\stack_mem[1] [2]),
    .C1(_016_),
    .C2(\stack_mem[2] [2]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a21boi_0 _180_ (
    .A1(\stack_mem[3] [2]),
    .A2(_078_),
    .B1_N(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o22ai_1 _181_ (
    .A1(EN),
    .A2(_069_),
    .B1(_083_),
    .B2(_040_),
    .Y(_003_[2])
  );
  sky130_fd_sc_hd__o22ai_1 _182_ (
    .A1(_066_),
    .A2(_009_),
    .B1(_017_),
    .B2(_062_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a221oi_1 _183_ (
    .A1(\stack_mem[0] [3]),
    .A2(_072_),
    .B1(_078_),
    .B2(\stack_mem[3] [3]),
    .C1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o22ai_1 _184_ (
    .A1(EN),
    .A2(_070_),
    .B1(_083_),
    .B2(_042_),
    .Y(_003_[3])
  );
  sky130_fd_sc_hd__a21oi_1 _185_ (
    .A1(SP[2]),
    .A2(_073_),
    .B1(RW),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _186_ (
    .A1(SP[2]),
    .A2(_078_),
    .B1(EN),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _187_ (
    .A1_N(_043_),
    .A2_N(_044_),
    .B1(EN),
    .B2(Rst),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _188_ (
    .A1(EN),
    .A2(_071_),
    .B1(_045_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__o21ai_0 _189_ (
    .A1(RW),
    .A2(_074_),
    .B1(_080_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and3_1 _190_ (
    .A(SP[0]),
    .B(EN),
    .C(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(EN),
    .A2(_046_),
    .B1(SP[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a211oi_1 _192_ (
    .A1(EN),
    .A2(Rst),
    .B1(_047_),
    .C1(_048_),
    .Y(_002_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(EN),
    .A2(_046_),
    .B1(SP[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _194_ (
    .A1(_073_),
    .A2(_079_),
    .B1(_080_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor3_1 _195_ (
    .A(RW),
    .B(_072_),
    .C(_078_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__or3_1 _196_ (
    .A(Rst),
    .B(_050_),
    .C(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _197_ (
    .A1(EN),
    .A2(_052_),
    .B1(_049_),
    .Y(_002_[1])
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_054_),
    .A2(EN),
    .B1(_045_),
    .Y(_002_[2])
  );
  sky130_fd_sc_hd__nor4_1 _199_ (
    .A(SP[2]),
    .B(RW),
    .C(SP[1]),
    .D(_083_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21o_1 _200_ (
    .A1(FULL),
    .A2(_083_),
    .B1(_053_),
    .X(_001_)
  );
  sky130_fd_sc_hd__dfxtp_1 _201_ (
    .CLK(clk),
    .D(_001_),
    .Q(FULL)
  );
  sky130_fd_sc_hd__dfxtp_1 _202_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(SP[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _203_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(SP[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _204_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(SP[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _205_ (
    .CLK(clk),
    .D(_000_),
    .Q(EMPTY)
  );
  sky130_fd_sc_hd__dfxtp_1 _206_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(dataOut[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _207_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(dataOut[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _208_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(dataOut[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _209_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(dataOut[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _210_ (
    .CLK(clk),
    .D(_004_[0]),
    .Q(\stack_mem[0] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _211_ (
    .CLK(clk),
    .D(_004_[1]),
    .Q(\stack_mem[0] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _212_ (
    .CLK(clk),
    .D(_004_[2]),
    .Q(\stack_mem[0] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _213_ (
    .CLK(clk),
    .D(_004_[3]),
    .Q(\stack_mem[0] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _214_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(\stack_mem[1] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _215_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(\stack_mem[1] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _216_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(\stack_mem[1] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(clk),
    .D(_005_[3]),
    .Q(\stack_mem[1] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(clk),
    .D(_006_[0]),
    .Q(\stack_mem[2] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(clk),
    .D(_006_[1]),
    .Q(\stack_mem[2] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(clk),
    .D(_006_[2]),
    .Q(\stack_mem[2] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(clk),
    .D(_006_[3]),
    .Q(\stack_mem[2] [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(clk),
    .D(_007_[0]),
    .Q(\stack_mem[3] [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(clk),
    .D(_007_[1]),
    .Q(\stack_mem[3] [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(clk),
    .D(_007_[2]),
    .Q(\stack_mem[3] [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(clk),
    .D(_007_[3]),
    .Q(\stack_mem[3] [3])
  );
endmodule
